[package]
name = "pallet-acuity-trusted-accounts"
version = "0.1.0"
description = "FRAME pallet for trusted accounts."
authors = ["Jonathan Brown <jbrown@acuity.social>"]
homepage = "https://acuity.social/"
edition = "2021"
license = "Apache-2.0"
publish = false
repository = "https://github.com/acuity-social/acuity-trusted-accounts-pallet"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.7.5", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2.11.1", default-features = false, features = ["derive"] }
polkadot-sdk = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-stable2512-3", default-features = false }

[features]
default = ["std"]
runtime-benchmarks = [
	"polkadot-sdk/frame-benchmarking",
	"polkadot-sdk/runtime-benchmarks",
]
std = [
	"codec/std",
	"polkadot-sdk/frame-support",
	"polkadot-sdk/frame-system",
	"polkadot-sdk/sp-io",
	"polkadot-sdk/sp-runtime",
	"polkadot-sdk/sp-std",
	"polkadot-sdk/std",
	"scale-info/std",
]
try-runtime = ["polkadot-sdk/try-runtime"]
