[package]
name = "pallet-acuity-trusted-accounts-rpc"
version = "0.1.0"
authors = ["Jonathan Brown <jbrown@acuity.social>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://acuity.social/"
repository = "https://github.com/acuity-social/acuity-trusted-accounts-pallet"
description = "RPC interface for the trusted accounts pallet."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.7.5", default-features = false }
jsonrpsee = { version = "0.24.10", features = ["client-core", "server", "macros"] }
pallet-acuity-trusted-accounts-rpc-runtime-api = { path = "./runtime-api" }
polkadot-sdk = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-stable2512-3", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"pallet-acuity-trusted-accounts-rpc-runtime-api/std",
	"polkadot-sdk/sp-api",
	"polkadot-sdk/sp-blockchain",
	"polkadot-sdk/sp-runtime",
	"polkadot-sdk/std",
]
